

export const CANCERS = {
  PATIENT: 'PATIENTTYPE',
  CANCER: 'CANCERTYPE',
  CANCER_ADD: 'CANCERTYPE_ADD',
  CANCER_EDIT: 'CANCERTYPE_EDIT',
  CANCER_DELETE: 'CANCERTYPE_DELETE',
  SUBCANCER1: 'SUBCANCER1TYPE',
  SUBCANCER2: 'SUBCANCER2TYPE',
  SUBCANCER3: 'SUBCANCER3TYPE',
  SUBCANCER: 'SUBCANCER',
  REGIMEN_DETAILS: 'REGIMEN_DETAILS',
  REGIMEN_DETAILSALL: 'REGIMEN_DETAILS_ALL',
  UPDATE_REGIMEN_IN_CANCER: 'UPDATE_REGIMEN_IN_CANCER'
};
