

export const CANCERS = {
  PATIENT: 'PATIENTTYPE',
  CANCER: 'CANCERTYPE',
  SUBCANCER1: 'SUBCANCER1TYPE',
  SUBCANCER2: 'SUBCANCER2TYPE',
  SUBCANCER3: 'SUBCANCER3TYPE',
  SUBCANCER: 'SUBCANCER',
  REGIMEN_DETAILS: 'REGIMEN_DETAILS',
  REGIMEN_DETAILSALL: 'REGIMEN_DETAILS_ALL'
};
